backend:
  name: github
  repo: mmtimes-insite/mmtimes   # replace with your GitHub username/repo
  branch: main
  auth_endpoint: https://mmtimes.in/api/auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
