backend:
  name: github
  repo: mmtimes-insite/mmtimes   # replace with your GitHub repo
  branch: main

media_folder: "assets/uploads"    # folder inside your repo
public_folder: "/assets/uploads"  # public URL path

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
