site_url: https://YOURDOMAIN.com   # example: https://mmtimes.in

backend:
  name: github
  repo: mmtimes-insite/mmtimes     # your repo name (user/repo format)
  branch: main                     # or the branch you use
  base_url: https://YOUR-OAUTH-URL # we’ll set this up in the login step

media_folder: "assets/uploads"     # where images are stored in repo
public_folder: "/assets/uploads"   # how site will use those images

collections:
  - name: "listings"
    label: "Listings"
    folder: "listings"             # CMS will put new entries here
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Price", name: "price", widget: "string", required: false }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Photos", name: "photos", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Description", name: "body", widget: "markdown" }
